# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait


class TestHogwarts:
    # 需要自行下载对应浏览器的 driver，需要注意版本，必须使用浏览器对应版本的 driver
    # setup_method 是执行在用例方法前，做一些之前条件
    def setup_method(self, method):
        # 使用 Chrome 浏览器
        self.driver = webdriver.Chrome()
        self.vars = {}

    # teardown_method 是执行在用例方法后，做一些清理操作
    def teardown_method(self, method):
        # 执行完用例后退出，关闭浏览器
        self.driver.quit()

    # 具体的测试用例，方法以 test 开头
    def test_test(self):
        # 打开某一个网址
        self.driver.get("https://testerhome.com/")
        # 隐式等待，这个设置是全局的，在设定的时间内等待对应的元素，超时会报错
        self.driver.implicitly_wait(5)
        # 设置浏览器的窗体大小，不是页面显示区域的大小
        self.driver.set_window_size(800, 600)
        # 寻找对应的元素，执行点击操作
        self.driver.find_element(By.LINK_TEXT, "社团").click()
        # 设置选择器
        element_locator = (By.LINK_TEXT, "霍格沃兹测试学院")
        # 显示等待，设定一个超时时间，默认每隔 0.5 秒查找一次，直到找到对应元素
        WebDriverWait(self.driver, 10, 0.5).until(expected_conditions.element_to_be_clickable(element_locator))
        element = self.driver.find_element(*element_locator)
        element.click()
